// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pocket_Cookbook_Backend.Models;

#nullable disable

namespace Pocket_Cookbook_Backend.Migrations
{
    [DbContext(typeof(CookbookContext))]
    [Migration("20230614154545_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Analyzedinstruction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("RecipeFK")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("RecipeFK");

                    b.ToTable("Analyzedinstruction");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Equipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("StepFK")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("localizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("StepFK");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Extendedingredient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("RecipeFK")
                        .HasColumnType("int");

                    b.Property<string>("aisle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("amount")
                        .HasColumnType("real");

                    b.Property<string>("consistency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("measuresid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameClean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("originalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("RecipeFK");

                    b.HasIndex("measuresid");

                    b.ToTable("Extendedingredient");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Ingredient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("StepFK")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("localizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("StepFK");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Meal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("number")
                        .HasColumnType("int");

                    b.Property<int?>("offset")
                        .HasColumnType("int");

                    b.Property<int?>("totalResults")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Measures", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("metricid")
                        .HasColumnType("int");

                    b.Property<int?>("usid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("metricid");

                    b.HasIndex("usid");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Metric", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float?>("amount")
                        .HasColumnType("real");

                    b.Property<string>("unitLong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unitShort")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Metric");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Recipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("aggregateLikes")
                        .HasColumnType("int");

                    b.Property<bool?>("cheap")
                        .HasColumnType("bit");

                    b.Property<int?>("cookingMinutes")
                        .HasColumnType("int");

                    b.Property<string>("creditsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("dairyFree")
                        .HasColumnType("bit");

                    b.Property<string>("gaps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("glutenFree")
                        .HasColumnType("bit");

                    b.Property<int?>("healthScore")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("lowFodmap")
                        .HasColumnType("bit");

                    b.Property<int?>("preparationMinutes")
                        .HasColumnType("int");

                    b.Property<float?>("pricePerServing")
                        .HasColumnType("real");

                    b.Property<int?>("readyInMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("servings")
                        .HasColumnType("int");

                    b.Property<string>("sourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sourceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spoonacularSourceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("sustainable")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("vegan")
                        .HasColumnType("bit");

                    b.Property<bool?>("vegetarian")
                        .HasColumnType("bit");

                    b.Property<bool?>("veryHealthy")
                        .HasColumnType("bit");

                    b.Property<bool?>("veryPopular")
                        .HasColumnType("bit");

                    b.Property<int?>("weightWatcherSmartPoints")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Result", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Meal")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Meal");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Step", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AnalyzedInstructionFK")
                        .HasColumnType("int");

                    b.Property<int?>("AnalyzedInstructionid")
                        .HasColumnType("int");

                    b.Property<int?>("number")
                        .HasColumnType("int");

                    b.Property<string>("step")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("AnalyzedInstructionid");

                    b.ToTable("Step");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Us", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float?>("amount")
                        .HasColumnType("real");

                    b.Property<string>("unitLong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unitShort")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Us");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Analyzedinstruction", b =>
                {
                    b.HasOne("Pocket_Cookbook_Backend.Models.Recipe", "Recipe")
                        .WithMany("analyzedInstructions")
                        .HasForeignKey("RecipeFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Equipment", b =>
                {
                    b.HasOne("Pocket_Cookbook_Backend.Models.Step", "Step")
                        .WithMany("equipment")
                        .HasForeignKey("StepFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Extendedingredient", b =>
                {
                    b.HasOne("Pocket_Cookbook_Backend.Models.Recipe", "Recipe")
                        .WithMany("extendedIngredients")
                        .HasForeignKey("RecipeFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pocket_Cookbook_Backend.Models.Measures", "measures")
                        .WithMany()
                        .HasForeignKey("measuresid");

                    b.Navigation("Recipe");

                    b.Navigation("measures");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Ingredient", b =>
                {
                    b.HasOne("Pocket_Cookbook_Backend.Models.Step", "Step")
                        .WithMany("ingredients")
                        .HasForeignKey("StepFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Measures", b =>
                {
                    b.HasOne("Pocket_Cookbook_Backend.Models.Metric", "metric")
                        .WithMany()
                        .HasForeignKey("metricid");

                    b.HasOne("Pocket_Cookbook_Backend.Models.Us", "us")
                        .WithMany()
                        .HasForeignKey("usid");

                    b.Navigation("metric");

                    b.Navigation("us");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Result", b =>
                {
                    b.HasOne("Pocket_Cookbook_Backend.Models.Meal", "meal")
                        .WithMany("results")
                        .HasForeignKey("Meal");

                    b.Navigation("meal");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Step", b =>
                {
                    b.HasOne("Pocket_Cookbook_Backend.Models.Analyzedinstruction", "AnalyzedInstruction")
                        .WithMany("steps")
                        .HasForeignKey("AnalyzedInstructionid");

                    b.Navigation("AnalyzedInstruction");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Analyzedinstruction", b =>
                {
                    b.Navigation("steps");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Meal", b =>
                {
                    b.Navigation("results");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Recipe", b =>
                {
                    b.Navigation("analyzedInstructions");

                    b.Navigation("extendedIngredients");
                });

            modelBuilder.Entity("Pocket_Cookbook_Backend.Models.Step", b =>
                {
                    b.Navigation("equipment");

                    b.Navigation("ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
